---


- hosts: all
  become: true
  tasks:

  - name: Оновлення індексу репозиторію
    apt:
      update_cache: yes

  - name: Встановлення пакету apache2
    apt:
      name: apache2
      state: latest

  - name: Добавляємо підтримку php для apache
    apt:
      name: libapache2-mod-php
      state: latest
